# Generated by Django 4.0.4 on 2024-09-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookc', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LifeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('false_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_facts', to='bookc.author')),
                ('true_authors', models.ManyToManyField(related_name='true_facts', to='bookc.author')),
            ],
        ),
    ]
