# Generated by Django 4.0.4 on 2024-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookc', '0005_author_lifefact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='FactAuthor',
        ),
    ]
