# Generated by Django 4.0.4 on 2024-09-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookc', '0006_rename_author_factauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
