# Generated by Django 4.0.4 on 2024-09-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookc', '0008_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.TextField(default='non-connu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
