# Generated by Django 4.0.4 on 2024-09-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookc', '0009_book_authors_book_published_date_book_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
